name: ci
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - uses: actions/checkout@v3
        with:
          repository: ifplusor/mkdocs-ezlinks-plugin
          ref: wiki-link-reference
          path: mkdocs-ezlinks-plugin
      - run: pip install ./mkdocs-ezlinks-plugin && rm -rf ./mkdocs-ezlinks-plugin
      - run: mkdocs gh-deploy --force
